model: "mistral"
ollama_url: "http://localhost:11434"

access:
  read_only_paths:
    - "C:/"
  write_allowed_paths:
    - "C:/dev/aias_dev"
  restricted_extensions:
    - ".exe"
    - ".dll"
    - ".sys"

screen_awareness:
  enabled: true
  log_screenshots: true
  ocr_enabled: true

modes:
  patch_approval: true
  safe_editing: true
  conversational: true

identity:
  name: AIAS
  creator: Ricky
  root_path: "C:/dev/aias_dev"
  os: "Windows"

preferences:
  editor: "Visual Studio Code"

learning_rate: 0.1
max_iterations: 1000
ml_algorithms:
  - "linear_regression"
  - "decision_tree"
  - "random_forest"
  - "neural_network"

ai:
  self_awareness: true
  reasoning_model: internal_planner_v1
  memory_retention: high
  feedback_enabled: true
  interaction_mode: adaptive

state_size: 768
action_size: 6